# Generated by Django 4.1.3 on 2022-12-29 08:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('elearns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_course_part',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='course_name',
            name='cat',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='course_name',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
